version: '3.8'
services:
  postgres:
    container_name: my_postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=meals_db
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

volumes:
  postgres-data:
